version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: hometask
      POSTGRES_PASSWORD: hometask
      POSTGRES_DB: hometask
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hometask"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: bash start.sh
    environment:
      DATABASE_URL: postgresql+asyncpg://hometask:hometask@postgres:5432/hometask
      SECRET_KEY: dev-secret-key-change-in-prod
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
        VITE_API_URL: http://backend:8000
    # environment:
    #   VITE_API_URL: http://localhost:8000

volumes:
  pgdata:
